/**
 * Seed de MasterMatch AI.
 *
 * ⚠️  DATOS DEMO: los programas aquí listados son ficticios/orientativos
 * (campo isDemoData = true) y NO proceden de fuentes oficiales. Sirven para
 * desarrollo y demostración del sistema de recomendación. Sustitúyelos por
 * datos verificados antes de cualquier uso real.
 */
import { PrismaClient, Modality, AdmissionDifficulty } from '@prisma/client';

const prisma = new PrismaClient();

type SeedMaster = {
  name: string;
  university: string;
  country: string;
  city: string;
  duration: string;
  price: number;
  language: string;
  modality: Modality;
  area: string;
  rankingScore: number;
  employabilityScore: number;
  networkingScore: number;
  internationalScore: number;
  admissionDifficulty: AdmissionDifficulty;
  requiredEnglishLevel: string;
  description: string;
  requirements: string[];
  careerOutcomes: string[];
  scholarshipInfo: string | null;
  officialUrl: string | null;
};

const masters: SeedMaster[] = [
  // ── Inteligencia Artificial ──────────────────────────────────────────────
  {
    name: 'Máster en Inteligencia Artificial',
    university: 'Universidad Politécnica de Madrid',
    country: 'España',
    city: 'Madrid',
    duration: '12 meses',
    price: 9500,
    language: 'Español',
    modality: Modality.onsite,
    area: 'Inteligencia Artificial',
    rankingScore: 82,
    employabilityScore: 88,
    networkingScore: 70,
    internationalScore: 60,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'B2',
    description: 'Formación avanzada en aprendizaje automático, visión por computador y NLP con enfoque aplicado.',
    requirements: ['Grado en Informática, Matemáticas o afín', 'Programación en Python', 'Nota media >= 7'],
    careerOutcomes: ['Machine Learning Engineer', 'Data Scientist', 'Investigador en IA'],
    scholarshipInfo: 'Becas de excelencia hasta el 30% de la matrícula.',
    officialUrl: 'https://example.edu/upm/master-ia',
  },
  {
    name: 'MSc Artificial Intelligence',
    university: 'University of Edinburgh',
    country: 'Reino Unido',
    city: 'Edimburgo',
    duration: '12 meses',
    price: 38000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Inteligencia Artificial',
    rankingScore: 95,
    employabilityScore: 92,
    networkingScore: 85,
    internationalScore: 90,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'Programa de referencia europea en IA, con fuerte componente investigador y de robótica.',
    requirements: ['Bachelor en disciplina cuantitativa', 'IELTS 6.5+', 'Cartas de recomendación'],
    careerOutcomes: ['AI Research Scientist', 'ML Engineer', 'Robotics Engineer'],
    scholarshipInfo: 'Becas internacionales competitivas y ayudas de investigación.',
    officialUrl: 'https://example.edu/edinburgh/msc-ai',
  },
  // ── Data Science ─────────────────────────────────────────────────────────
  {
    name: 'MSc Data Science',
    university: 'Delft University of Technology',
    country: 'Países Bajos',
    city: 'Delft',
    duration: '24 meses',
    price: 21000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Data Science',
    rankingScore: 90,
    employabilityScore: 90,
    networkingScore: 78,
    internationalScore: 92,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Ciencia de datos con énfasis en ingeniería de datos a gran escala y sistemas distribuidos.',
    requirements: ['Bachelor STEM', 'Álgebra y estadística', 'TOEFL/IELTS'],
    careerOutcomes: ['Data Engineer', 'Data Scientist', 'Analytics Lead'],
    scholarshipInfo: 'Holland Scholarship para estudiantes no-EU.',
    officialUrl: 'https://example.edu/tudelft/msc-data-science',
  },
  {
    name: 'Máster en Ciencia de Datos y Big Data',
    university: 'Universitat de Barcelona',
    country: 'España',
    city: 'Barcelona',
    duration: '12 meses',
    price: 8900,
    language: 'Español',
    modality: Modality.hybrid,
    area: 'Data Science',
    rankingScore: 76,
    employabilityScore: 84,
    networkingScore: 66,
    internationalScore: 64,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B1',
    description: 'Programa práctico en analítica, visualización y machine learning aplicado a negocio.',
    requirements: ['Grado universitario', 'Conocimientos de estadística', 'Programación básica'],
    careerOutcomes: ['Data Analyst', 'BI Specialist', 'Data Scientist Junior'],
    scholarshipInfo: 'Pago fraccionado y becas parciales por mérito.',
    officialUrl: 'https://example.edu/ub/master-data-science',
  },
  // ── Finanzas ─────────────────────────────────────────────────────────────
  {
    name: 'MSc Finance',
    university: 'London School of Economics',
    country: 'Reino Unido',
    city: 'Londres',
    duration: '10 meses',
    price: 41000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Finanzas',
    rankingScore: 96,
    employabilityScore: 94,
    networkingScore: 95,
    internationalScore: 93,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'Finanzas cuantitativas y corporativas con acceso directo a la City de Londres.',
    requirements: ['Bachelor con alto expediente', 'GMAT/GRE recomendado', 'IELTS 7.0'],
    careerOutcomes: ['Investment Banker', 'Quant Analyst', 'Portfolio Manager'],
    scholarshipInfo: 'Becas parciales por mérito muy competitivas.',
    officialUrl: 'https://example.edu/lse/msc-finance',
  },
  {
    name: 'Máster en Finanzas Corporativas',
    university: 'IE University',
    country: 'España',
    city: 'Madrid',
    duration: '10 meses',
    price: 32000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Finanzas',
    rankingScore: 88,
    employabilityScore: 90,
    networkingScore: 88,
    internationalScore: 86,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Programa internacional en finanzas corporativas, M&A y private equity.',
    requirements: ['Grado universitario', 'Inglés avanzado', 'Entrevista de admisión'],
    careerOutcomes: ['Corporate Finance Analyst', 'M&A Associate', 'Consultor financiero'],
    scholarshipInfo: 'Ayudas al talento de hasta el 35%.',
    officialUrl: 'https://example.edu/ie/master-finanzas',
  },
  // ── Marketing ────────────────────────────────────────────────────────────
  {
    name: 'MSc Marketing Management',
    university: 'Bocconi University',
    country: 'Italia',
    city: 'Milán',
    duration: '24 meses',
    price: 16000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Marketing',
    rankingScore: 89,
    employabilityScore: 87,
    networkingScore: 84,
    internationalScore: 88,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Marketing estratégico y digital con fuerte orientación a datos y branding.',
    requirements: ['Bachelor en ADE/afín', 'Inglés C1', 'Carta de motivación'],
    careerOutcomes: ['Brand Manager', 'Digital Marketing Lead', 'Product Marketing Manager'],
    scholarshipInfo: 'Becas por mérito y necesidad económica.',
    officialUrl: 'https://example.edu/bocconi/msc-marketing',
  },
  {
    name: 'Máster en Marketing Digital y Analítica',
    university: 'ESIC Business & Marketing School',
    country: 'España',
    city: 'Valencia',
    duration: '9 meses',
    price: 12500,
    language: 'Español',
    modality: Modality.hybrid,
    area: 'Marketing',
    rankingScore: 72,
    employabilityScore: 82,
    networkingScore: 70,
    internationalScore: 58,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B1',
    description: 'Marketing digital orientado a performance, SEO/SEM, social media y analítica web.',
    requirements: ['Titulación universitaria o experiencia profesional', 'Entrevista'],
    careerOutcomes: ['Digital Marketing Manager', 'Growth Specialist', 'SEO/SEM Manager'],
    scholarshipInfo: 'Descuentos por matrícula anticipada.',
    officialUrl: 'https://example.edu/esic/master-marketing-digital',
  },
  // ── Derecho ──────────────────────────────────────────────────────────────
  {
    name: 'LLM International Business Law',
    university: 'Leiden University',
    country: 'Países Bajos',
    city: 'Leiden',
    duration: '12 meses',
    price: 19500,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Derecho',
    rankingScore: 87,
    employabilityScore: 80,
    networkingScore: 76,
    internationalScore: 90,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Derecho mercantil internacional, arbitraje y regulación de mercados globales.',
    requirements: ['Grado en Derecho', 'Inglés C1', 'Expediente sólido'],
    careerOutcomes: ['Abogado mercantil internacional', 'Legal Counsel', 'Compliance Officer'],
    scholarshipInfo: 'Leiden Excellence Scholarship.',
    officialUrl: 'https://example.edu/leiden/llm-business-law',
  },
  {
    name: 'Máster de Acceso a la Abogacía',
    university: 'Universidad de Navarra',
    country: 'España',
    city: 'Pamplona',
    duration: '18 meses',
    price: 14000,
    language: 'Español',
    modality: Modality.onsite,
    area: 'Derecho',
    rankingScore: 78,
    employabilityScore: 83,
    networkingScore: 72,
    internationalScore: 55,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B1',
    description: 'Habilita para el ejercicio de la abogacía con prácticas en despachos de referencia.',
    requirements: ['Grado en Derecho', 'Prácticas obligatorias'],
    careerOutcomes: ['Abogado/a', 'Asesor jurídico', 'Procurador'],
    scholarshipInfo: 'Becas por expediente y ayudas al estudio.',
    officialUrl: 'https://example.edu/unav/master-abogacia',
  },
  // ── MBA ──────────────────────────────────────────────────────────────────
  {
    name: 'Full-Time MBA',
    university: 'INSEAD',
    country: 'Francia',
    city: 'Fontainebleau',
    duration: '10 meses',
    price: 98500,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'MBA',
    rankingScore: 98,
    employabilityScore: 96,
    networkingScore: 98,
    internationalScore: 99,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'MBA global de élite con la red de alumni más internacional del mundo.',
    requirements: ['Experiencia laboral 2+ años', 'GMAT alto', 'Inglés C1', 'Entrevistas'],
    careerOutcomes: ['Consultor estratégico', 'Director general', 'Fundador de startup'],
    scholarshipInfo: 'Amplio programa de becas por diversidad y mérito.',
    officialUrl: 'https://example.edu/insead/mba',
  },
  {
    name: 'International MBA',
    university: 'IESE Business School',
    country: 'España',
    city: 'Barcelona',
    duration: '19 meses',
    price: 99000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'MBA',
    rankingScore: 94,
    employabilityScore: 93,
    networkingScore: 92,
    internationalScore: 95,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'MBA basado en el método del caso con rotaciones internacionales.',
    requirements: ['Experiencia profesional', 'GMAT/GRE', 'Entrevista'],
    careerOutcomes: ['Manager', 'Consultor', 'Emprendedor'],
    scholarshipInfo: 'Becas IESE y financiación a través de partners bancarios.',
    officialUrl: 'https://example.edu/iese/international-mba',
  },
  // ── Seguros ──────────────────────────────────────────────────────────────
  {
    name: 'Máster en Dirección de Entidades Aseguradoras y Financieras',
    university: 'Universidad Pontificia de Comillas (ICADE)',
    country: 'España',
    city: 'Madrid',
    duration: '12 meses',
    price: 16500,
    language: 'Español',
    modality: Modality.onsite,
    area: 'Seguros',
    rankingScore: 80,
    employabilityScore: 89,
    networkingScore: 82,
    internationalScore: 62,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B2',
    description: 'Gestión técnica y directiva del sector asegurador: actuarial, riesgos y Solvencia II.',
    requirements: ['Grado en ADE, Economía, Matemáticas o afín', 'Entrevista'],
    careerOutcomes: ['Actuario', 'Gestor de riesgos', 'Director de entidad aseguradora'],
    scholarshipInfo: 'Becas del sector asegurador (Fundación MAPFRE y otras).',
    officialUrl: 'https://example.edu/comillas/master-seguros',
  },
  {
    name: 'MSc Actuarial Science',
    university: 'University College Dublin',
    country: 'Irlanda',
    city: 'Dublín',
    duration: '12 meses',
    price: 24000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Seguros',
    rankingScore: 84,
    employabilityScore: 91,
    networkingScore: 75,
    internationalScore: 80,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Ciencia actuarial con exenciones de exámenes profesionales (IFoA).',
    requirements: ['Bachelor cuantitativo', 'Probabilidad y estadística', 'IELTS 6.5'],
    careerOutcomes: ['Actuario', 'Risk Analyst', 'Pricing Specialist'],
    scholarshipInfo: 'UCD Global Excellence Scholarships.',
    officialUrl: 'https://example.edu/ucd/msc-actuarial',
  },
  // ── Consultoría ──────────────────────────────────────────────────────────
  {
    name: 'MSc Management & Strategy',
    university: 'HEC Paris',
    country: 'Francia',
    city: 'París',
    duration: '16 meses',
    price: 42000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Consultoría',
    rankingScore: 93,
    employabilityScore: 92,
    networkingScore: 90,
    internationalScore: 91,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'Estrategia y consultoría con acceso directo a las grandes firmas (MBB).',
    requirements: ['Bachelor con expediente alto', 'GMAT/GRE', 'Entrevistas'],
    careerOutcomes: ['Strategy Consultant', 'Management Consultant', 'Business Analyst'],
    scholarshipInfo: 'Becas Eiffel y ayudas de la escuela.',
    officialUrl: 'https://example.edu/hec/msc-strategy',
  },
  {
    name: 'Máster en Consultoría de Negocio y Transformación Digital',
    university: 'EOI Escuela de Organización Industrial',
    country: 'España',
    city: 'Madrid',
    duration: '10 meses',
    price: 13800,
    language: 'Español',
    modality: Modality.hybrid,
    area: 'Consultoría',
    rankingScore: 71,
    employabilityScore: 85,
    networkingScore: 74,
    internationalScore: 60,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B2',
    description: 'Consultoría orientada a transformación digital, procesos y gestión del cambio.',
    requirements: ['Titulación universitaria', 'Entrevista personal'],
    careerOutcomes: ['Consultor de negocio', 'Project Manager', 'Analista de transformación'],
    scholarshipInfo: 'Becas parciales cofinanciadas por fondos públicos.',
    officialUrl: 'https://example.edu/eoi/master-consultoria',
  },
  // ── Ingeniería ───────────────────────────────────────────────────────────
  {
    name: 'MSc Mechanical Engineering',
    university: 'Technical University of Munich',
    country: 'Alemania',
    city: 'Múnich',
    duration: '24 meses',
    price: 3000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Ingeniería',
    rankingScore: 92,
    employabilityScore: 90,
    networkingScore: 80,
    internationalScore: 88,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Ingeniería mecánica avanzada con vínculos con la industria automovilística alemana.',
    requirements: ['Bachelor en Ingeniería', 'Inglés C1', 'Expediente sólido'],
    careerOutcomes: ['Ingeniero de diseño', 'R&D Engineer', 'Ingeniero de producto'],
    scholarshipInfo: 'Matrícula pública muy baja; becas DAAD disponibles.',
    officialUrl: 'https://example.edu/tum/msc-mechanical',
  },
  {
    name: 'Máster en Ingeniería de Telecomunicación',
    university: 'Universitat Politècnica de Catalunya',
    country: 'España',
    city: 'Barcelona',
    duration: '24 meses',
    price: 7400,
    language: 'Español',
    modality: Modality.onsite,
    area: 'Ingeniería',
    rankingScore: 81,
    employabilityScore: 88,
    networkingScore: 68,
    internationalScore: 70,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'B2',
    description: 'Redes, sistemas y comunicaciones con especialización en 5G y fotónica.',
    requirements: ['Grado en Ingeniería de Telecomunicación o afín', 'Nota media >= 6.5'],
    careerOutcomes: ['Ingeniero de telecomunicaciones', 'Network Engineer', 'Ingeniero de RF'],
    scholarshipInfo: 'Becas de colaboración y ayudas autonómicas.',
    officialUrl: 'https://example.edu/upc/master-teleco',
  },
  // ── Emprendimiento ───────────────────────────────────────────────────────
  {
    name: 'MS Entrepreneurship & Innovation',
    university: 'University of California, Berkeley',
    country: 'Estados Unidos',
    city: 'Berkeley',
    duration: '12 meses',
    price: 70000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Emprendimiento',
    rankingScore: 95,
    employabilityScore: 90,
    networkingScore: 96,
    internationalScore: 92,
    admissionDifficulty: AdmissionDifficulty.very_high,
    requiredEnglishLevel: 'C1',
    description: 'Emprendimiento tecnológico en el corazón de Silicon Valley, con mentores y VCs.',
    requirements: ['Bachelor', 'TOEFL alto', 'Proyecto/idea de negocio', 'Entrevistas'],
    careerOutcomes: ['Fundador de startup', 'Product Manager', 'Venture Analyst'],
    scholarshipInfo: 'Becas por mérito y fondos para proyectos emprendedores.',
    officialUrl: 'https://example.edu/berkeley/ms-entrepreneurship',
  },
  {
    name: 'Máster en Emprendimiento e Innovación',
    university: 'Mondragon Unibertsitatea',
    country: 'España',
    city: 'Mondragón',
    duration: '12 meses',
    price: 9800,
    language: 'Español',
    modality: Modality.hybrid,
    area: 'Emprendimiento',
    rankingScore: 70,
    employabilityScore: 84,
    networkingScore: 78,
    internationalScore: 66,
    admissionDifficulty: AdmissionDifficulty.low,
    requiredEnglishLevel: 'B1',
    description: 'Programa "learning by doing" para crear una startup real durante el curso.',
    requirements: ['Titulación universitaria', 'Motivación emprendedora'],
    careerOutcomes: ['Emprendedor', 'Intraemprendedor', 'Gestor de innovación'],
    scholarshipInfo: 'Ayudas para proyectos y aceleración.',
    officialUrl: 'https://example.edu/mondragon/master-emprendimiento',
  },
  // ── Extra para enriquecer el catálogo ────────────────────────────────────
  {
    name: 'MSc Business Analytics',
    university: 'Trinity College Dublin',
    country: 'Irlanda',
    city: 'Dublín',
    duration: '12 meses',
    price: 23000,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Data Science',
    rankingScore: 85,
    employabilityScore: 89,
    networkingScore: 80,
    internationalScore: 84,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Analítica de negocio, optimización y data-driven decision making.',
    requirements: ['Bachelor', 'Conocimientos cuantitativos', 'IELTS 6.5'],
    careerOutcomes: ['Business Analyst', 'Data Scientist', 'Operations Analyst'],
    scholarshipInfo: 'Becas Trinity para estudiantes internacionales.',
    officialUrl: 'https://example.edu/tcd/msc-business-analytics',
  },
  {
    name: 'Máster en Inteligencia Artificial Aplicada a los Negocios',
    university: 'Politecnico di Milano',
    country: 'Italia',
    city: 'Milán',
    duration: '12 meses',
    price: 14500,
    language: 'Inglés',
    modality: Modality.online,
    area: 'Inteligencia Artificial',
    rankingScore: 86,
    employabilityScore: 87,
    networkingScore: 72,
    internationalScore: 82,
    admissionDifficulty: AdmissionDifficulty.medium,
    requiredEnglishLevel: 'B2',
    description: 'IA aplicada a la empresa: automatización, analítica avanzada y casos reales, 100% online.',
    requirements: ['Titulación universitaria', 'Inglés B2', 'Programación básica deseable'],
    careerOutcomes: ['AI Product Manager', 'Business Data Scientist', 'Consultor de IA'],
    scholarshipInfo: 'Descuentos por inscripción temprana.',
    officialUrl: 'https://example.edu/polimi/master-ai-business',
  },
  {
    name: 'MSc Financial Technology (FinTech)',
    university: 'University of Amsterdam',
    country: 'Países Bajos',
    city: 'Ámsterdam',
    duration: '12 meses',
    price: 18500,
    language: 'Inglés',
    modality: Modality.onsite,
    area: 'Finanzas',
    rankingScore: 87,
    employabilityScore: 89,
    networkingScore: 83,
    internationalScore: 88,
    admissionDifficulty: AdmissionDifficulty.high,
    requiredEnglishLevel: 'C1',
    description: 'Intersección de finanzas y tecnología: blockchain, pagos digitales y data en banca.',
    requirements: ['Bachelor en disciplina cuantitativa', 'Inglés C1'],
    careerOutcomes: ['FinTech Analyst', 'Quant Developer', 'Product Manager en banca digital'],
    scholarshipInfo: 'Amsterdam Merit Scholarship.',
    officialUrl: 'https://example.edu/uva/msc-fintech',
  },
];

async function main(): Promise<void> {
  console.log('🌱 Sembrando base de datos de MasterMatch AI (datos DEMO)...');

  // Orden de borrado respetando relaciones.
  await prisma.recommendation.deleteMany();
  await prisma.savedMaster.deleteMany();
  await prisma.masterProgram.deleteMany();

  const result = await prisma.masterProgram.createMany({
    data: masters.map((m) => ({ ...m, isDemoData: true })),
  });

  console.log(`✅ Insertados ${result.count} másteres demo en ${new Set(masters.map((m) => m.country)).size} países.`);
}

main()
  .catch((error) => {
    console.error('❌ Error al sembrar la base de datos:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
